server:
  port: 8889

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wzh0717/config.git
          default-label: master
          search-paths: respo
          username:
          password:
      label: master





